### ISSUE TITLE
Provider is not working

### ISSUE THREAD

**Issue by stvnwrgs** [Samsung-AG/terraform-provider-execute#1]
I get the following output with the example:
```
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * execute_command.commands2: Provider doesn't support resource: execute_command
  * execute_command.commands1: Provider doesn't support resource: execute_command
```

**Comment by maratoid** [comment]
Hello! 

Did you make sure that the provider binary is in terraform's path?

**Comment by stvnwrgs** [comment]
Yep. It is in the same path as the other terraform-* files. It has 0775 rights and i also added it to the providers list.

```
» cat ~/.terraformrc
providers {
    execute = "/usr/local/bin/terraform-provider-exec"
}
````

i also tried `execute_command` as key, but its not working. Maybe it is an issue with the naming of the resource?

**Comment by maratoid** [comment]
I believe the binary should be named 'terraform-provider-execute'

perhaps try renaming it to that (and optionally doing)

```
providers {
    execute = "/usr/local/bin/terraform-provider-execute"
}
```

in the .terraformrc ?

**Comment by stvnwrgs** [comment]
Good idea. But it didn't fix the problem either.

```
Errors:

  * execute_command.commands: Provider doesn't support resource: execute_command

```
.terraformrc : https://terraform.io/docs/plugins/basics.html

What is your terraform version? Don't you use the .terraformrc file?

**Comment by maratoid** [comment]
No I do not.

I just have the provider in the path of terraform binary

What's your environment like? I'll try to replicate it and see what could be wrong. 

Also, if you are on a mac you can install terraform with homebrew and then use our provider tap:

```
brew install terraform
brew tap 'Samsung-AG/terraform-provider-execute'
brew install terraform-provider-execute
```

**Comment by stvnwrgs** [comment]
Great. That helped. Thanks!
